[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
optimizer = true
optimizer_runs = 100_000
solc = '0.8.27'
evm_version = 'cancun'
bytecode_hash = 'none'
out = 'out'
libs = ['lib']
remappings = []
fs_permissions = [{ access = "write", path = "./reports" }]
gas_reports = ['*']

[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
quote_style = 'single'
wrap_comments = true
ignore = ['out/**', 'lib/**']

[lint]
ignore = ['out/**', 'lib/**']

[doc]
out = 'docs'
ignore = ['out/**', 'lib/**']

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
optimism = "${RPC_OPTIMISM}"
avalanche = "${RPC_AVALANCHE}"
polygon = "${RPC_POLYGON}"
arbitrum = "${RPC_ARBITRUM}"
metis = "${RPC_METIS}"
base = "${RPC_BASE}"
gnosis = "${RPC_GNOSIS}"
bnb = "${RPC_BNB}"
celo = "${RPC_CELO}"

# See more config options https://book.getfoundry.sh/reference/config/overview
