name: Test

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    uses: bgd-labs/github-workflows/.github/workflows/foundry-lint.yml@main
  test:
    uses: bgd-labs/github-workflows/.github/workflows/foundry-test.yml@main
    with:
      compareGas: true
      compareSize: true
      compareLcov: true
    secrets: inherit
